# Don't load upstream wl2771 module, doesn't work
blacklist wl1271
blacklist wl1271_sdio

# Don't auto-load wl12xx until later in boot...
# need /media/system-config mounted for symlink to NVS file
blacklist wl12xx
blacklist wl12xx_sdio